#:import Toolbar kivymd.toolbar.Toolbar
#:import ThemeManager kivymd.theming.ThemeManager
#:import NavigationDrawer kivymd.navigationdrawer.MDNavigationDrawer
#:import NavigationDrawer kivymd.navigationdrawer.NavigationLayout
#:import MDList kivymd.list.MDList
#:import OneLineListItem kivymd.list.OneLineListItem
#:import TwoLineListItem kivymd.list.TwoLineListItem
#:import ThreeLineListItem kivymd.list.ThreeLineListItem
#:import OneLineAvatarListItem kivymd.list.OneLineAvatarListItem
#:import OneLineIconListItem kivymd.list.OneLineIconListItem
#:import OneLineAvatarIconListItem kivymd.list.OneLineAvatarIconListItem
#:import MDTextField kivymd.textfields.MDTextField
#:import MDDropdownMenu kivymd.menu.MDDropdownMenu
#:import MDTabbedPanel kivymd.tabs.MDTabbedPanel

#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import colors kivymd.color_definitions.colors
#:import MDTabbedPanel kivymd.tabs.MDTabbedPanel
#:import MDTab kivymd.tabs.MDTab
#:import MDThemePicker kivymd.theme_picker.MDThemePicker

#:import NavigationDrawerToolbar kivymd.navigationdrawer.NavigationDrawerToolbar

#:import MDTextField kivymd.textfields.MDTextField

#:import MDProgressBar kivymd.progressbar.MDProgressBar
##:import MDSpinner kivymd.spinner.MDSpinner

<MainBox>:
	#id: datos
	#orientation: 'vertical'
	#lay_nav: nav_layout
	pisos_nav: nav_drawer
	Screen:
		name: 'login'
		Login:
			id: tab_panel
			tab_display_mode: 'text'
			MDTab:
				name: 'login_tab' 
				text: "Login"
				BoxLayout:
					size_hint_y: None
					height: dp(400)
					padding: dp(200)
					orientation: 'vertical'
					spacing: 10
					MDTextField:
						id: usr
						text: app.config.get('WENU', 'USER')
						hint_text: 'Usuario'
						message: "Debe ingresar un usuario"
						required: True
						message_mode: "on_error"
					MDTextField:
						id: password
						text: app.config.get('WENU', 'PASS')
						hint_text: "Contraseña"
						message: "Debe ingresar una contraseña"
						required: True
						password: True
						message_mode: "on_error"
			MDTab:
				name: 'config_tab'
				text: "Configuración"
				BoxLayout:
					size_hint_y: None
					height: dp(400)
					padding: dp(200)
					orientation: 'vertical'
					spacing: 10
					MDTextField:
						id: ip
						text: app.config.get('WENU', 'SERVER')
						hint_text: 'Servidor ip'
						message: "Debe ingresar una ip del servidor al cual desea conectarse"
						required: True
						message_mode: "on_error"
					MDTextField:
						id: port
						text: '8000'
						hint_text: "Puerto"
						message: "Debe ingresar un puerto al cual conectarse"
						required: True
						message_mode: "on_error"
			MDRaisedButton:
				text: 'Conectar'
				pos_hint: {'center_x': 0.5, 'center_y': 0.6}
				on_press: self.parent.conectar(usr.text, password.text, ip.text)
	Load:
		id: progressbar
		name: 'progressbar'
		prog_b: progress_bar
		BoxLayout:
			id: box_progress
			orientation:'vertical'
			padding: '8dp'
			spacing: '20dp'
			#prog_b: progress_bar
			
			MDLabel:
				size_hint: None, None
				pos_hint: {'center_x': .55, 'center_y':1}
				text: 'Cargando...'
			
			MDProgressBar:
				id: progress_bar
				min: 0
				max: 100
				value: 0
				text: 'Cargando...'
	Screen:
		name: 'main'
		BoxLayout:
			id: datos
			orientation: 'vertical'
			lay_nav: nav_layout
			pisos_nav: nav_drawer
			Toolbar:
				md_bg_color: app.theme_cls.primary_color
				background_palette: 'Primary'
				background_hue: '500'
				id: toolbar
				title: 'Datos sensores'
				background_color: self.theme_cls.primary_color
				left_action_items: [['menu', lambda x: self.parent.lay_nav.toggle_nav_drawer()]]
				right_action_items: [['dots-vertical', lambda x: MDDropdownMenu(items=root.menu_items, width_mult=2).open(self)]]
			NavigationLayout:
				id: nav_layout
				PisosNavDrawer:
					title: "Pisos"
					id: nav_drawer
					NavigationDrawerToolbar:
						title: "Pisos"
						id: nav_drawer_tool
				ScreenManager:
					id: scr_mngr
					Screen:
						name: 'bottomsheet'



#<NavigationDraweIconButton>:
#	icon: 'checkbox-blank-circle'

#
<Mota>:
	background_color: [0.0, 0.0, 0.0, 0.0]
	size_hint: (0.1, .1)
	markup: True
	valign: 'bottom'

<Piso>:
	#flayout: flayout_id
	#title_color: [ 33/255., 150/255., 243/255., .9 ]
	#background: 'atlas:/data/images/defaulttheme/button_pressed'
	#background_color: [0,0,0,0]
	FloatLayout:
		id: flayout_id
		size: self.parent.size
		MDLabel:
			id: fecha
			#size_hint: (0.8, .1)
			pos_hint: {'top': 1.44, 'right': 1.01}
			text: 'Ultima actualización: '
			#markup: True

#MDSpinner:
#	id: spinner
#	size_hint: None, None
#	size: dp(46), dp(46)
#	pos_hint: {'center_x': 0.5, 'center_y': 0.5}
#	active: True

#<MotaImage>:
	
